version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/recipe-app
permissions:
  - object: /home/ubuntu/recipe-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clean_old_images.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu